### ISSUE TITLE
After Updating To 5.25 the addon is missing 'riglogic" Did not have this in 0.5.4

### ISSUE THREAD

**Issue by jbrute** [poly-hammer/meta-human-dna-addon#273]
cannot import name 'riglogic' from 'bl_ext.user_default.meta_human_dna.bindings' (/Users/jonathanaldenberg/Library/Application Support/Blender/4.5/extensions/user_default/meta_human_dna/bindings/__init__.py)

i've used the 0.8 template of the build tool,  Im not sure what I am doing wrong, as I had no problems with version  0.5.4

please advice what to do

**Comment by jack-yao91** [comment]
What is your OS platform and CPU architecture?

**Comment by jbrute** [comment]
Windows 11 AMD Radeon 610M - AMD R9 9955HX3D

blender 5
nVidia RTX 5080 16.0Gb GDDR7 150W TGP

**Comment by Gamerage** [comment]
Same here - Blender output

<img width="1150" height="63" alt="Image" src="https://github.com/user-attachments/assets/f63b59ce-47d1-4feb-86b3-3a2f5bb7a345" />

Windows 11 - 14700k - RTX3090

**Comment by jack-yao91** [comment]
Ok make sure to re-copy the template repo for the [build workflow](https://github.com/poly-hammer/poly-hammer-build-tool-workflow), so that you are using version 0.8.1 of the build tool. Based on the error message you both are getting, I am guessing your riglogic bindings are in the wrong folder. (this would happen if you built addon version 0.5.25 with an earlier version of the build tool, because the bindings location was moved)

So I would just follow this video from the beginning and re-copy the template repo fresh and rebuild and see if that fixes your problem.
https://youtu.be/BAyCV8GwmCM?si=sbwhYdOORb8vJIpI

**Comment by jbrute** [comment]
As I've mentioned, I've already used the latest version of the build tool. In any case, I've, just to be sure, replicated the exact steps of the video with the latest build tool, and again run into the same error. I haven't changed my steps for the 0.5.4 version of the add-on, which didn't provide me with any problems. So again, please advise me what to do, because these steps are clearly not working as of this moment. Thank you for your support.

**Comment by Gamerage** [comment]
I used the latest template provided from this link - https://github.com/poly-hammer/poly-hammer-build-tool-workflow

Update - I first uninstalled the old addon, restarted Blender, installed the new addon and it went in without a hitch - opened my file got a message to migrate the .blend file to this new version and seems to be working - will test some more

Update - I find the face board to be super laggy in pose mode - is there a way to improve that? Opened a ticket as it's a separate issue.

**Comment by RoboElementalist** [comment]
hi, unfortunately I'm getting a similar error, I've tried doing a complete uninstall of the old version, rebuilding the addon with the new .8.1 build tool but unfortunately get this error

<img width="1360" height="208" alt="Image" src="https://github.com/user-attachments/assets/8642f9e2-bf32-4805-a83e-40d72d49f923" />
<img width="1024" height="95" alt="Image" src="https://github.com/user-attachments/assets/2926a355-2a21-4da6-a438-7de735437733" />

**Comment by jbrute** [comment]
I don't think there is a solution yet.

**Comment by jack-yao91** [comment]
Ok looks like you might have rebuilt with an older version of the build tool. For addon version 0.5.25 and higher, you need to build with build tool version 0.8.1 or higher.
https://github.com/poly-hammer/poly-hammer-build-tool-workflow

The best way to update is just re-copy that template repo, and run through the setup again.
https://www.youtube.com/watch?v=BAyCV8GwmCM

Once you do that, uninstall the old addon, shutdown blender, start blender, and install the new built version.

**Comment by jbrute** [comment]
@jack-yao91 Sorry, but most people in this threat are specially mentioning using the latest build.  Can you please provide an update to a real solution and not advising to "just turn it off and on again."

many thanks for your support and help
It is a fantastic add on.

**Comment by jack-yao91** [comment]
Sorry, I don't mean to seem repetitive, but if you can triple check your steps and versions when you built this, cause I just ran through these steps a 5 minutes ago and it is working. Also, we do know that 100+ users have been able to install the latest version successfully.

But to give more details. If you inspect the contents of your built .zip file and look at this folder `bindings/windows/x64/py311` you should see the compiled bindings here.

<img width="580" height="284" alt="Image" src="https://github.com/user-attachments/assets/8b690c24-aef3-4d6e-a96d-9953119a5a18" />

If these are missing, then it is because it was built with an older build tool version.

If these are here, I know it sounds really simple, but uninstalling, shutting down blender, starting blender, then installing latest it most likely the culprit. The python interpreter won't resource these modules until the blender process has been shutdown and restarted. 

If you can check these things and provide anymore details, I can help you trouble shoot further.

**Comment by atemgfx** [comment]
I've never seen anything like it. Even in an email, it's just a stupid copy-pasted message without any attempt to understand that the issue is affecting multiple users simultaneously on the same version. It's like everyone's suddenly become idiots. Since I got the add-on, I've found more answers from the community than from the developers. Please, give us access to a Discord server so we can connect more easily.

Anyway, @Gamerage's solution worked for me. I uninstalled all available versions, then closed Blender, saving my preferences. Once restarted, I launched the installation using drag and drop, and it worked for me personally.

**Comment by jbrute** [comment]
> @Gamerage
Dont think they have solution at the moment, I am affraid, maybe when the add-on goes out of beta they will have time to fix it.
