### ISSUE TITLE
Riglogic AttributeError when importing DNA into Blender (Both 4.5 & 5.0)

### ISSUE THREAD

**Issue by ItSourby** [poly-hammer/meta-human-dna-addon#239]
**Addon Version:** 0.5.3

**Blender Versions Tested:** 4.5.1 & 5.0.1

Hello! Im not particularly technical, though trust Im giving my all to understand this and get it working. I apologies if my formatting here is off the norm too, though I'll provide information to the best of my ability here.

I've redone all steps from creating a new repo onwards, to no success. 
This is the case in both Blender 4.5.1 and Blender 5.0.
Recreating the steps:
- I am able to successfully build the ZIP from my repo.
- I get the addon installed into Blender with no issues. 

Problems Occur:

> On attempt to import a .dna file _(with attempts from both Unreal's existing Ada.dna file on their repo, and my own exports from UE5)_ I am greeted with this error message:
> `Python: Traceback (most recent call last):
>   File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\meta_human_dna\operators.py", line 718, in execute
>     valid, message = body_component.ingest()
>                      ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\meta_human_dna\components\body.py", line 54, in ingest
>     valid, message = self.dna_importer.run()
>                      ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\meta_human_dna\dna_io\importer.py", line 661, in run
>     self.setup_swing_bones()
>   File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\meta_human_dna\dna_io\importer.py", line 603, in setup_swing_bones
>     for swing_index in range(self._dna_reader.getSwingCount()):
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'riglogic.BinaryStreamReader' object has no attribute 'getSwingCount'. Did you mean: 'getJointCount'?
> `

Any help here would be much appreciated, and I'd be more than happy to provide more details if needed! Though truly with all else being followed to the letter, I'm not sure whats going wrong here... 
Attached is an image of the file after the traceback error is dismissed:
<img width="1261" height="957" alt="Image" src="https://github.com/user-attachments/assets/beb69751-53bd-4531-89aa-b7f6efb6e69b" />

Thus far I've
- I've recreated all the builds and files to try again, no success. 
- Attempting to link to the appropriate rig and re-evaluate. This also fails.

**Comment by jack-yao91** [comment]
Hey, it looks like you built with an older version of the build tool. You will need to build with version 0.7.1 or higher. I would just re-copy the template repo
https://github.com/poly-hammer/poly-hammer-build-tool-workflow

And then follow the setup video again and build latest
https://www.youtube.com/watch?v=BAyCV8GwmCM

Let me know if that helps!

**Comment by ItSourby** [comment]
Hey, thanks for the quick response!

 I did give this another shot, a couple of times, and it doesnt seem to want to use 0.7.1 no matter what I do... I create a new repo using the template you linked, but the only options I have are as such:
<img width="528" height="765" alt="Image" src="https://github.com/user-attachments/assets/214782e5-00d0-4c57-b248-4ab022ba79b3" />

Not entirely sure how to use the more up-to-date release, as it doesn't give me any more options I'm aware of when simply clicking "Use this template"

I created a new access token, new repo, new builds, but these are still my only options. Happy to hear and try anything you think might work here! :D

**Comment by ItSourby** [comment]
I thought it best to give a step by step of what I'm doing, hopefully the issue is something minor on my part that's easy to fix! 
(apologies, a couple of these screenshots look a bit brighter because of windows HDR misbehaving whilst screenshotting...)

I understand it that the version being used is consistently 0.5.3 and of course expect it to fail, but I cant see a way to force it to use 0.7.1. As before, any help is much appreciated, and thank you for your time and effort here! 

<details>  
  <summary> 1 - Click on "Use This Template" </summary>    
  <div class="image-container">    
    <img width="3817" height="1908" alt="Image" src="https://github.com/user-attachments/assets/ce58293b-834d-450c-a0b5-aecf34096d63" />
    </a>
  </div>    
</details>

<details>  
  <summary> 2 - Create a private copy of the repo </summary>    
  <div class="image-container">    
    <img width="3817" height="1908" alt="Image" src="https://github.com/user-attachments/assets/31b978f9-fddf-4ba9-a2ea-5129b188b178" />
    </a>
  </div>    
</details>

<details>  
  <summary> 3 - Create an Access Token </summary>    
  <div class="image-container">    
    <img width="3817" height="1908" alt="Image" src="https://github.com/user-attachments/assets/fd14cdd5-ecd9-49b9-8393-9c37ad780f55" />
    </a>
  </div>    
</details>

<details>  
  <summary> 4 - Run Workflow for Build</summary>    
  <div class="image-container">    
    <img width="3817" height="1908" alt="Image" src="https://github.com/user-attachments/assets/ce10e6bc-d94a-46a9-ad19-0d210a160f8e" />
    </a>
  </div>    
</details>

<details>  
  <summary> 5 - Download Build</summary>    
  <div class="image-container">    
    <img width="3817" height="1908" alt="Image" src="https://github.com/user-attachments/assets/e4e7fc1d-a2b6-4a04-b51d-30dc07c34efd" />
    </a>
  </div>    
</details>

<details>  
  <summary> 6 - Install and Test Build</summary>    
  <div class="image-container">    
    <img width="2558" height="1390" alt="Image" src="https://github.com/user-attachments/assets/c8dc1ef6-06b8-430e-87bc-1e60306e0a93" /> <img width="2558" height="1390" alt="Image" src="https://github.com/user-attachments/assets/823f88f1-1bac-49e3-8685-6b8623d670e2" /> <img width="2558" height="1390" alt="Image" src="https://github.com/user-attachments/assets/24b74aee-f9d1-4a88-9e2c-d99bfe53d186" />
    </a>
  </div>    
</details>

Hope this is somewhat useful for troubleshooting?

**Comment by jack-yao91** [comment]
Ok thanks for outlining your steps. It looks like you are doing everything correctly build-wise (also 0.5.4 just went out a few minutes ago btw)

My guess, is that you have 2 Meta-Human DNA addons installed in blender, since you are still getting the error about those missing attributes. Can you check `Edit > Preferences > Add-ons` and search for `Meta-Human DNA`?

Also make sure you uninstall the old addon from blender, and then shutdown blender. (this allows the old python code to unload from memory) Then start blender and install your latest addon build. Let me know if that works.
